#This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyOpenSSL
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Chrome 119
      uses: browser-actions/setup-chrome@v2
      id: setup-chrome
      with:
        chrome-version: 119
    - name: Pack extension with Chrome
      run: |
        sudo apt-get update && sudo apt-get install -y xvfb
        xvfb-run --auto-servernum "${{ steps.setup-chrome.outputs.chrome-path }}" --pack-extension=./Tampermonkey --pack-extension-key=./key.pem --no-message-box
        mv ./Tampermonkey.crx ./Tampermonkey_5-1-1.crx
    - name: Upload CRX artifact
      uses: actions/upload-artifact@v7
      with:
        path: Tampermonkey_5-1-1.crx
        archive: false
        if-no-files-found: error
        retention-days: 1
